### PR TITLE
Ranking

### PR DESCRIPTION
**Pull request by timludikar**
I could be missing something... Just wanted to update for 17.3 and 17.4 ranking. Nice work!

### CODE REVIEW

**Comment by thielCole** [comment]
Hey @timludikar , thanks for helping out. 

Could you redo the commits, I see three commits that reference the prod build taht have 10k+ line changes. When I deploy the changes then I can do the prod build, but I would like to keep the changes as simple as possible when I merge. 

I think you are on the right track, just simplify the commits for only adding references to sorting by score value for workout 3 and 4.

**Comment by timludikar** [comment]
@thielCole in that case, does it make sense to update the `.gitignore` file to include the `/dist` folder?

**Comment by thielCole** [comment]
Hmm yeah your probably right. Before I was using the .gitignore to do a deployment to my elastic beanstalk instance, but I can change that.

**Comment by thielCole** [comment]
Looks much cleaner, thanks.

**Comment by captaincole** [comment]
I'll try and add this by the end of the day.

**Pull request merged**
